Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
